### ISSUE TITLE
Wrong assembly versions

### ISSUE THREAD

**Issue by ronaldbarendse** [gauffininteractive/onetrueerror.client#12]
The NuGet version and assemly versions don't match, e.g.:
- [OneTrueError.Client 1.0.0](https://www.nuget.org/packages/OneTrueError.Client/1.0.0) = OneTrueError.Client, Version=1.1.1.0
- [OneTrueError.Client.AspNet 1.0.0](https://www.nuget.org/packages/OneTrueError.Client.AspNet/1.0.0) = OneTrueError.Client.AspNet, Version=1.1.0.0
- [OneTrueError.Client.log4net 1.0.0](https://www.nuget.org/packages/OneTrueError.Client.log4net/1.0.0) = OneTrueError.Client.Log4Net, Version=1.1.0.0 (also has different casing)

To make it even worse, [OneTrueError.Client 1.0.1](https://www.nuget.org/packages/OneTrueError.Client/1.0.1) has the correct assembly version (1.0.1.0), but this breaks the reference on the other packages that were build against the higher version (1.1.1.0).

You could publish 1.0.1 versions to NuGet for all other packages (with the correct - although lower - assembly version 1.0.1.0), so all versions match again. Otherwise, releasing a OneTrueError.Client 1.1.2 (or higher) version should fix the reference part...

Maybe setting up automated build, versioning and packaging using [MyGet](https://myget.org/), [Visual Studio Team Services](https://www.visualstudio.com/en-us/docs/package/build/team-build-nuget#publish-packages-created-by-your-build) or [AppVeyor](https://www.appveyor.com/) could help you out here! You can find more info in this 3 part blog post: https://blogs.msdn.microsoft.com/visualstudioalm/2016/05/03/versioning-nuget-packages-cd-1/.

**Comment by ronaldbarendse** [comment]
Oh, and remove the Nuget\ReadMe.txt content file from the NuGet package! Please follow the NuGet documentation to correctly add a readme file: https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#adding-a-readme-and-other-files.

**Comment by gauffininteractive** [comment]
thank you for pointing it out. All packages have been corrected.

**Comment by ronaldbarendse** [comment]
OneTrueError.Client 1.0.3 has broken this again, because the assembly version is below 1.1.1 again (NuGet version 1.0.2 had assembly version 1.1.2.0). Please release corrected versions for all packages!

Fow now, the workaround is to add an assembly binding (under `configuration\runtime\assemblyBinding` in every project):

```
<dependentAssembly>
  <assemblyIdentity name="OneTrueError.Client" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-1.1.1.0" newVersion="1.0.3.0" />
</dependentAssembly>
```

**Comment by jgauffin** [comment]
I've updated all client libraries so that they use the new Visual Studio 2017 csproj-file. Thus the version will always match between the package version and the assembly version. All client libraries also have their own repository now.

I am currently creating a new deployment flow:

1. Our new build server will build everything on every commit
2. If unit tests passes, it will deploy to our new internal beta nuget feed.
3. The build server will run a trigger which makes our automated integration tests download the new nuget package and run integration tests against the OSS server
4. If that works, the new package will deployed to nuget.org

I'm currently implementing step 3, will update this issue when everything is complete.
